"""
Converts the .JSONL files generated by `build_dataset.py` into a single
objectified .JSONL file suitable for uploading to the Hugging Face Hub, where
each line (which was an array originally) is now wrapped within an object with
a "conversations" key.
"""

import json
import argparse
from uuid import uuid4


def main():
    """
    The main entry point of the script. Converts the files.
    """

    parser = argparse.ArgumentParser(
        description="Convert JSONL files to objectified format"
    )
    parser.add_argument("input_file", help="Input JSONL file path")
    parser.add_argument("output_file", help="Output JSONL file path")

    args = parser.parse_args()
    input_filename = args.input_file
    output_filename = args.output_file

    with open(input_filename, "r", encoding="utf-8") as infile, open(
        output_filename, "w", encoding="utf-8"
    ) as outfile:
        for line in infile:
            conversation = json.loads(line)
            obj = {"conversations": conversation, "id": str(uuid4())[:8]}
            outfile.write(json.dumps(obj, ensure_ascii=False) + "\n")


if __name__ == "__main__":
    main()
